### ISSUE TITLE
Move lightweight call to init rather than every function signature

### ISSUE THREAD

**Issue by limx0** [liampauling/betfairlightweight#105]
Would it be possible to just pass a `lightweight` flag to the APIClient rather than to every function? I think it's more likely people would use it for all/none of their API calls rather than for specific API calls. 

Thoughts?

**Comment by liampauling** [comment]
You mean like this:

https://github.com/liampauling/betfairlightweight/blob/master/betfairlightweight/apiclient.py#L8

**Comment by limx0** [comment]
Sorry - I got caught off-gaurd by the lightweight kwargs everywhere. 

def list_competitions(self, filter=market_filter(), locale=None, session=None, **lightweight=None**)

Cheers
