### ISSUE TITLE
Keepalive returned no json

### ISSUE THREAD

**Issue by oughtotrade** [liampauling/betfairlightweight#110]
Today I had some issues with the keepalive not returning json.
Of course this caused an exception where it could not decode the json. 

Should unexpected, non-json responses be caught more tidily?

I wasn't able to debug whether the keepAlive succeeded despite not returning json nor whether this was just a temporary issue with betfair.

**Comment by liampauling** [comment]
This was raised on the slack group as well, weird as I wasn't impacted, moving to the rest endpoint #96 would probably prevent the error issue.

**Comment by oughtotrade** [comment]
Thanks! You can close this issue if you think #96 supersedes it.
