### ISSUE TITLE
Python 2.7 compatibility

### ISSUE THREAD

**Issue by synapticarbors** [liampauling/betfairlightweight#21]
I wanted to play around with this package but due to some constraints with other tooling, couldn't upgrade to Python 3. I spent a little bit of time making a few modifications such that the test suite passes under both Python 2.7 and 3.5. I'm happy to open a pull request, but wanted to know if you were open to possibly merging it or if you'd prefer to keep it Python 3 only for code purity (which I totally understand).

**Comment by liampauling** [comment]
Hi, could you not use virtualenv? I think the only library limiting it to 3 is the use of Enum's which I want to remove soon anyway. Out of interest how many changes did you have to make? 

If it's simple could be persuaded to merge...

**Comment by synapticarbors** [comment]
Closed by #22
