### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by liampauling** [liampauling/betfairlightweight#26]
@synapticarbors regarding OpenSSL, this is a requirement of Requests, what errors are you getting on the conda build?

**Comment by synapticarbors** [comment]
See: https://travis-ci.org/conda-forge/staged-recipes/builds/185126419#L1005

I'm not sure why the conda-forge CI isn't pulling in OpenSSL as a requirement for the python 3.4 build:

https://travis-ci.org/conda-forge/staged-recipes/builds/185126419#L886-L916

it does when it builds python 2.7:

https://travis-ci.org/conda-forge/staged-recipes/builds/185126419#L279-L322

I'm hoping that one of the conda-forge core developers will provide some feedback. I could just add it as an explicit dependency, but I want to first clarify why it's missing.
