### ISSUE TITLE
Certificate handling

### ISSUE THREAD

**Issue by fracek** [liampauling/betfairlightweight#30]
I find certificate handling a bit confusing at the moment, since I would expect it to work like for requests. That is the ```certs``` argument for ```APIClient``` should be either a path to a .pem file, or a tuple with the paths to cert and key files.

Also, [here](https://github.com/liampauling/betfairlightweight/blob/master/betfairlightweight/baseclient.py#L119) you want to use ```os.path.join``, because if `self.certs` doesn't end with `/`, then the generated path is wrong, but I was not sure about opening a PR just for that.

**Comment by liampauling** [comment]
Going to fix the latter on 0.9.4, which will have your pull request as well (thanks)

The cert property currently makes things easier by assuming you have your certs in a folder so all you have to do is provide a directory instead.

**Comment by fracek** [comment]
I see. I tried it again but it seems to fail because my folder has `crt`, `crs`, `key`, and `pem` files in it. Also to point to the correct directory (`../certs/`) I need to pass `certs`, since `BaseClient` expects the path relative to the parent directory. 

It's easy to work around (made a folder with just crt and key files, passed different path as certs), but I found it confusing.

**Comment by fracek** [comment]
I worked a possible solution i[n my fork](https://github.com/fracek/betfairlightweight/tree/fix-cert-path). If you like it I can open a PR for it too.

**Comment by liampauling** [comment]
You able to open a PR and I will have a look my side, thanks.

**Comment by liampauling** [comment]
All working my side so have pushed 0.9.4 to master, thanks!

**Comment by joelpob** [comment]
It might be worth explaining the certs vs. cert_files difference somewhere. I got confused with how the parameters are used (i.e. I was passing certs='certs/' instead of certs='parentdir/certs') and I was also confused with what type of certificate format is required (I was actually using .pem files, and not .key and .crt files). 

Burned a good 20 minutes looking at the code to work this out. :)
