### ISSUE TITLE
Configure logging

### ISSUE THREAD

**Issue by agberk** [liampauling/betfairlightweight#43]
At the moment logging statements are called directly from the `logging` module (e.g. `logging.info(...)`) - this implicitly creates a root logger and adds a default handler if it doesn't exist.

This can cause unwanted output for application developers.

The following links propose some best practice for logging in a library:
http://docs.python-guide.org/en/latest/writing/logging/
https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

My understanding from the links above would be to make the following changes in `betfairlightweight`:

1. Add the following to `betfairlightweight.__init__.py`:

```python
# Set default logging handler to avoid "No handler found" warnings.
import logging
try:  # Python 2.7+
    from logging import NullHandler
except ImportError:
    class NullHandler(logging.Handler):
        def emit(self, record):
            pass

logging.getLogger(__name__).addHandler(NullHandler())
```

This would mean by default nothing would get logged by library unless configured by the user (this is optional since if the next point is implemented, it's easy for the user to configure the library to disable logging).

2. In all modules which use `logging.*` add the following at the module level:

```python
logger = logging.getLogger(__name__)
```

And then switch all `logging.*` statements to `logger.*` statements.

I'm happy to submit a pull requests with the changes, but I wanted to check whether you had any issues with it or other ideas first.

**Comment by liampauling** [comment]
Sounds good, you are right that the user should configure and the current setup isn't 'correct' although most of the logging is for streaming/debugging.

I assume you will do the following in the files which require logging statements:

`logger = getLogger(__name__)`

**Comment by agberk** [comment]
Yes - I've added that statement in the relevant files in #44
