### ISSUE TITLE
BetfairStream doesn't set _running to False after a socket exception in _read_loop

### ISSUE THREAD

**Issue by agberk** [liampauling/betfairlightweight#45]
The BetfairStream class has a member `_running` which is used to indicate if the stream is... running or not.

If you run a BetfairStream in async mode and you get a socket exception in [_read_loop](https://github.com/liampauling/betfairlightweight/blob/master/betfairlightweight/streaming/betfairstream.py#L135-L159), there's no way to determine if the thread has died as the class doesn't store a reference to the thread it starts and `_running` isn't updated in the case of the SocketError exceptions; checking `_running` from an outside thread would indicate that it's still going.

I think the best way to solve this is just with a `finally` block when `_running` is set to `False`. I'm not sure whether any socket cleanup needs to be done in case of an error? My brief googling didn't give me a definitive answer.

Raised PR #46

**Comment by liampauling** [comment]
Ah nice find, you can see that under the try except there is some code which attempts to shutdown the socket. Regarding the pull it might be cleaner if it called self.stop() unless you disagree?

**Comment by agberk** [comment]
I clearly wasn't thinking when I added that `finally` block - the loop is only ever going to get executed once with that in there.

I agree about calling the `stop` method instead.

I've changed the raises to just `logging.error(...)` calls and then added `self.stop()`.

I changed the `test_read_loop_error` test to call `_read_loop()` and then `assert not self.betfair_stream._running` - not sure if this is the best way to test it?

If the raise is removed and changed to a `logging.error` call, it means that `exceptions.SocketError` is actually no longer used anywhere in the package; do you want to get rid of it?

When this PR gets merged, I'll update the logging PR to switch the naked `logging.error` call to obtain a module logger and then use that.

**Comment by liampauling** [comment]
I need an error to be raised if there is a timeout or another error or my framework will not know that there is an issue and the stream needs to be restarted / reconnect. I agree with the addition of self.stop() but I think an error has to be raised.

The use of logging also conflicts with the logging update I am about to merge to master.

**Comment by agberk** [comment]
I think I misunderstood your reason for calling `stop()` - I thought it was so that it would break out of the loop and call the socket cleanup code.

Clearly if the exception is still raised, it will never reach that cleanup code even after calling `stop()` and having `_running` set to False.

However, just calling `stop()` before `raise` will set `_running` to False which will allow me to check the aliveness of the thread, and still throw the exception.

Shall I just create a new branch / PR and put that in there since there's a load of rubbish which isn't applicable now in this one?

**Comment by liampauling** [comment]
Hmm you are right raising the error means the socket will never be cleaned unless the entire while loop is placed in a try/except and a finally with the stop + cleanup code but that doesn't seem very pythonic. 

I think the logical thing to do is to move the clean up code into stop(), because the socket gets recreated during the start() process anyway.

**Comment by agberk** [comment]
Agreed, I think the socket cleanup code should go into `stop()`.

**Comment by agberk** [comment]
I've redone the PR in #52
