### ISSUE TITLE
Add appveyor to run tests on Windows

### ISSUE THREAD

**Issue by synapticarbors** [liampauling/betfairlightweight#47]
Given my experience trying to get betfairlightweight built as a conda package on conda-forge, I think it would be good to have tests run on Windows via appveyor:

https://www.appveyor.com

Like other CI platforms, it's free for open source projects. This would help the project catch platform dependent errors during development.

**Comment by liampauling** [comment]
Thanks, I have added / linked appveyor in a new branch, if you have experience in using it are you able to write the build file?

**Comment by synapticarbors** [comment]
I haven't set appveyor up before, but I can try to get it running sometime soon.
