### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by liampauling** [liampauling/betfairlightweight#51]
I have created a slack group to discuss any issues:

betfairlightweight.slack.com

**Comment by agberk** [comment]
Looks like one needs an invite to get onto it? Can I get one? :)

**Comment by liampauling** [comment]
Annoyingly I have to invite you using your email address or I can whitelist an email domain, do you use gmail? The alternative is to create a web app to host the invite process which is way too much effort.

**Comment by agberk** [comment]
Yup, I'm on gmail

**Comment by liampauling** [comment]
And I cant add gmail, can you send me an email, its [surname][firstname]@gmail.com, so my username on here backwards.

**Comment by favetelinguis** [comment]
Im getting no account found for team when trying to join?

**Comment by liampauling** [comment]
Please send me an email.

**Comment by tarak2014** [comment]
Hi Liam,

Thanks for the quick reply.

I am using the streaming example given in https://github.com/liampauling/betfa...lestreaming.py.
I can see the streaming data coming from Betfair by printing market_book.streaming_update attribute.

I have below queries:
1. How can we get the available ladders for back and lay (atb and atl) for every runner at that point of time.
2. How can we get the best available ladder for back and lay (batb and batl) for every runner at that point of time.
3. I have gone through the Exchange Stream documentation provided by Betfair and understood the logic behind building price cache (https://docs.developer.betfair.com/d...ingapricecache). Should we build it manually or is this functionality already available in your solution.

Being a newbie to python and betfair I am trying to understand the code of betfairlightweight API (https://github.com/liampauling/betfair).

Any help would be greatly appreciated.
Thanks in advance.

Cheers,
Tarak

**Comment by liampauling** [comment]
1 / 2 just involved you asking for the data in the [market_data_filter](https://docs.developer.betfair.com/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API#ExchangeStreamAPI-Marketdatafieldfiltering/MarketDataFilter)

3 bflw handles all the heavy lifting with the cache etc. you can just pull off the latest MarketBook and work with that, you don't need to look at 'streaming_update'


Join the slack group for questions like this.

https://betfairlightweight.herokuapp.com/
