### ISSUE TITLE
Not returning markets in the same order as eventIds

### ISSUE THREAD

**Issue by skyw00lker** [liampauling/betfairlightweight#59]
market_ids does not get returned in the same way as in the betfair API

```
event_ids = [28200940, 28200941, 28200939, 28200937, 28202622, 28188158, 28202623, 28188159, 28202621, 28188157, 28202619, 28202616, 28202617, 28202614, 28202615, 28196677, 28202626, 28188160, 28202625, 28188176, 28188177]

markets = betfairclient.trading.betting.list_market_catalogue(
            max_results=100,
            filter=filters.market_filter(
                 event_ids=event_ids,
                 market_type_codes = ["MATCH_ODDS"]
            ))
```
yields mismatch between market_id and eventId

I looked briefly at the code but could not see any reordering, I could've missed something to. :)

**Comment by liampauling** [comment]
What order are you expecting? I don't think betfair will return the same order as the request.

I just tested between the [visualiser](https://developers.betfair.com/visualisers/api-ng-sports-operations/) and lightweight and its exactly the same.
