### ISSUE TITLE
API parameters which are not required should be kwargs

### ISSUE THREAD

**Issue by agberk** [liampauling/betfairlightweight#64]
Looking at the cancelOrders API call:

http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/cancelOrders
https://github.com/liampauling/betfairlightweight/blob/master/betfairlightweight/endpoints/betting.py#L303-L320

According to the Betfair documentation there are no required parameters - however the `Betting.cancel_orders` method requires `market_id` and `instructions` as positional args.

I think the most intuitive way to do things is that positional args correspond to required parameters and kwargs correspond to parameters which are not required.

At the moment in this specific instance (`cancel_orders`), the user is required to pass parameters which they do not want to use and it's not immediately obvious what they should set it these parameters to if they don't want them to be used.

The `utils.clean_locals(...)` function will not include keys whose value is None so any parameters which are not required can just be defaulted to None.

To resolve the issue `Betting.cancel_orders` needs to have `market_id` and `instructions` changed to kwargs defaulted to None.

I haven't looked at any of the other methods but there's the possibility there are other instances of this, so I think a full pass of the methods on the endpoints should performed, comparing the args / kwargs to the correspondng Betfair API required / not required parameters.

I'm happy to both look through the API calls and put the resulting changes into a PR.

**Comment by liampauling** [comment]
Yeh I have missed this, would be good to get a second pair of eyes on the endpoints if you have the time? However I believe cancel orders is the only request with this quirk?

**Comment by rozzac90** [comment]
I went through the betting and account endpoints and I do not believe this quirk is present anywhere else, I think this can be closed now?
