### ISSUE TITLE
Offer on camelCase

### ISSUE THREAD

**Issue by codoff** [liampauling/betfairlightweight#85]
Hi, @liampauling.

I think it's not a good idea to use snake_case in func/arg names.
Of course, it is accepted in the python, but the API-NG is done in camelCase mode. Continuous conversions are hardly reasonable. Also, this adds confusion to the code, for example, when creating an object, we use one style
`cancel_bet = filters.cancel_instruction(bet_id=bet.id)` 

and accessing it's fields in a different style
`foo(cancel_bet["betId"])`

It's easy to make a typo that will be difficult to catch. Working with API-NG documentation you get used to camel style, etc. Therefore, I suggest using camelCase in the library.

What do you think?

**Comment by liampauling** [comment]
Agreed that its not ideal but not going to start breaking python rules.

I think you could probably do something clever with __getattr__.
